### ISSUE TITLE
Password Strength

### ISSUE THREAD

**Issue by spencer-carver** [aymanjebril2/finanseer#20]
Options:
1. https://github.com/danielmiessler/SecLists/blob/master/Passwords/Common-Credentials/10-million-password-list-top-1000000.txt ensure password is not present in this list (top 10M passwords), and has some minimum length (6? 8?)
2. https://stackoverflow.com/questions/19605150/regex-for-password-must-contain-at-least-eight-characters-at-least-one-number-a choose an appropriate password regex

Can we rely on Glenn Williams or Sean Matthiesen to have a discussion around best practices and recommendations here as well? will reach out

**Comment by Just-Another-Github-Acct** [comment]
The current wisdom in password requirements is to have users set long passphrases with few if no additional requirements. For example, your app could require that users create a passphrase that is at least 25-30 characters long, but has no other requirements (upper/lowercase letters, numbers, special characters). This way, a user can create a password that is a combination of random words - much easier to remember, and much harder to crack or randomly guess (so long as the user doesn't use a common phrase like a song lyric).
There are also additional considerations around building a login system, which are handily summarized here (link credit to Sean Matthiesen):
https://auth0.com/blog/dont-pass-on-the-new-nist-password-guidelines/
For more on passphrases:
https://www.zdnet.com/article/fbi-recommends-passphrases-over-password-complexity/

**Comment by spencer-carver** [comment]
our initial implementation is a 16-character minimum pass phrase. We're adding the appropriate tooltip in #46
